apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k22
  namespace: default
spec:
  runStrategy: Halted
  dataVolumeTemplates:
    - metadata:
        name: win2k22-root
      spec:
        storage:
          storageClassName: rook-ceph-block
          volumeMode: Filesystem
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 40Gi
        source:
          blank: {}
  template:
    metadata:
      labels:
        kubevirt.io/vm: win2k22
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 3Gi
        machine:
          type: q35
        devices:
          disks:
            - name: rootdisk
              bootOrder: 2
              disk:
                bus: virtio
            - name: windows-iso
              bootOrder: 1
              cdrom:
                bus: sata
            - name: virtio-drivers
              cdrom:
                bus: sata
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
          inputs:
            - type: tablet
              bus: usb
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: win2k22-root
        - name: windows-iso
          persistentVolumeClaim:
            claimName: win2k22-iso
        - name: virtio-drivers
          containerDisk:
            image: quay.io/kubevirt/virtio-container-disk:v1.9.0
