apiVersion: v1
kind: Service
metadata:
  name: win2k22-rdp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: win2k22
  ports:
    - name: rdp
      port: 3389
      targetPort: 3389
      protocol: TCP
